### ISSUE TITLE
Hello, I want to know how you got the pictures of your models(such as "2020-ZJUCG-Final-Project\model\basic voxel\cone-1\preview.png")

### ISSUE THREAD

**Issue by zhiyingf** [KoonanHyakukeiZu/2020-ZJUCG-Final-Project#2]

**Comment by bdwhst** [comment]
We got these preview pictures directly from modeling software (Blender). All the models in our project were collected from the Internet.



发自我的iPhone


------------------ Original ------------------
From: zhiyingf ***@***.***&gt;
Date: Mon,Aug 2,2021 10:05 PM
To: KoonanHyakukeiZu/2020-ZJUCG-Final-Project ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [KoonanHyakukeiZu/2020-ZJUCG-Final-Project] Hello, I want to know how you got the pictures of your models(such as "2020-ZJUCG-Final-Project\model\basic voxel\cone-1\preview.png") (#2)
